# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a75d885fd4a7fee1381af5dfb09f4f3a0787c69505601a7571f171b025b96c2279b058fa832be6cf098950946999266912c2029be9a7b55f7e3126edc258c67

test:
  secret_key_base: 7712b2c03dbfd88f4413a35b03f04d1befa9364f0d984840a88c5f41a6fce8b4c3011e33fdcfcb4e68de918fdbd9f56a5b60083eba8018398eb44c3a57e9529d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
